channels:
- conda-forge
- bioconda
dependencies:
- python=3.11
- dask
- snakemake
- pandas
- pyiron_base
- h5io
- h5io_browser
- pyiron_contrib
- pympipool
- bidict
- cloudpickle
- python-graphviz
- matplotlib-base
- toposort
- typeguard
- pip:
  - pyiron_workflow
